modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/TerraformersMC/Biolith/issues"
license = "LGPL-3.0"

[[mods]]
modId = "biolith"
version = "${version}"
displayName = "Biolith"
displayURL="https://modrinth.com/mod/biolith"
authors = "TerraformersMC, gniftygnome"
description = '''
Terraformers' world generation utilities
'''
logoFile = "assets/biolith/logo.png"
[[dependencies.biolith]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.biolith]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"