package com.terraformersmc.biolith.api.surface;

import net.minecraft.core.Holder;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.TagKey;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.chunk.BlockColumn;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.levelgen.ChunkTerrainBuilder;
import net.minecraft.world.level.levelgen.NoiseColumn;
import net.minecraft.world.level.levelgen.material.MaterialRuleContext;
import org.jspecify.annotations.Nullable;

/**
 * BiolithSurfaceBuilder provides an interface used by the surface builder mixin to inject surface builders.
 * Because surface builders are no longer a first class citizen in Minecraft, this interface is simpler than
 * the pre-1.18.2 surface builder interfaces.
 * <p></p>
 * All you have to do is provide a generator method which modifies each existing BlockColumn as required for
 * the surface you wish to generate and call the setBiomeKey or setBiomeTag method to specify valid biomes
 * to modify.
 */
@SuppressWarnings("unused")
public abstract class BiolithSurfaceBuilder {
	@Nullable ResourceKey<Biome> biomeKey;
	@Nullable TagKey<Biome> biomeTag;

	/**
	 * The generate() method will be called after noise is used to set the surface height and the noise-based
	 * default material block column has been computed (when badlands pillars are created).  This is before the
	 * application of biome-specific material rules.
	 *
	 * @param ruleContext   The {@link ChunkTerrainBuilder}'s {@link MaterialRuleContext}
	 * @param column        The noise column to modify as generated by the surface noise
	 * @param rand          The random provider specified by the chunk generator
	 * @param chunk         The chunk being generated
	 * @param surfaceBiome  The biome assigned to the block column at the level surface
	 * @param x             The X coordinate of the column being generated
	 * @param z             The Y coordinate of the column being generated
	 * @param initialHeight The height of the level surface as generated by the surface noise
	 */
	public void generate(MaterialRuleContext ruleContext, NoiseColumn column, RandomSource rand, ChunkAccess chunk, Biome surfaceBiome, int x, int z, int initialHeight) {}

	/**
	 * The generateLate() method will be called at the end of column generation (when icebergs are created).
	 * This is after the application of carvers and aquifers.
	 *
	 * @param ruleContext   The {@link ChunkTerrainBuilder}'s {@link MaterialRuleContext}
	 * @param column        The block column to modify as generated by the surface noise and carvers
	 * @param rand          The random provider specified by the chunk generator
	 * @param chunk         The chunk being generated
	 * @param surfaceBiome  The biome assigned to the block column at the level surface
	 * @param x             The X coordinate of the column being generated
	 * @param z             The Y coordinate of the column being generated
	 * @param initialHeight The height of the level surface as generated by the surface noise
	 */
	public void generateLate(MaterialRuleContext ruleContext, BlockColumn column, RandomSource rand, ChunkAccess chunk, Biome surfaceBiome, int x, int z, int initialHeight) {}

	/**
	 * This method will be called for every block column generated by Minecraft to determine whether to apply each
	 * injected surface builder, so keep the logic here as simple as possible.  The default implementation which
	 * evaluates biomes set in setBiomeKey() and setBiomeTag() is sufficient for most requirements:
	 *
	 * <pre>{@code
	 * public boolean filterBiome(Holder<Biome> biome) {
	 *     if (biomeKey != null && biome.is(biomeKey)) {
	 *         return true;
	 *     } else if (biomeTag != null) {
	 *         return biome.is(biomeTag);
	 *     }
	 *     return false;
	 * }
	 * }</pre>
	 *
	 * @param biome Registry entry of the currently processing biome
	 * @return      True if the surface rule is applicable to the given biome
	 */
	public boolean filterBiome(Holder<Biome> biome) {
		if (biomeKey != null && biome.is(biomeKey)) {
			return true;
		} else if (biomeTag != null) {
			return biome.is(biomeTag);
		}

		return false;
	}

	/**
	 * Sets the biome registry key of the biome to which this surface builder applies.
	 *
	 * @param biomeKey Registry key of the biome to which this surface builder applies.
	 * @return         This method returns the surface builder being configured.
	 */
	public BiolithSurfaceBuilder setBiomeKey(ResourceKey<Biome> biomeKey) {
		this.biomeKey = biomeKey;

		return this;
	}

	/**
	 * Sets the biome tag key of the biomes to which this surface builder applies.
	 *
	 * @param biomeTag Tag containing biomes to which this surface builder applies.
	 * @return         This method returns the surface builder being configured.
	 */
	public BiolithSurfaceBuilder setBiomeTag(TagKey<Biome> biomeTag) {
		this.biomeTag = biomeTag;

		return this;
	}
}
